#!/usr/bin/with-contenv bash

PUID=${PUID:-1099}
PGID=${PGID:-1099}

addgroup -S -g "$PGID" minecraft
adduser -u "$PUID" -S -H -D -s /sbin/nologin minecraft -G minecraft

echo "User minecraft(uid:$(id -u minecraft), gid:$(id -g minecraft))"

